### ISSUE TITLE
LDAPAllSyncJob claims to sync everything but doesn't

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-ldap#11]
https://github.com/silverstripe/silverstripe-ldap/blob/master/src/Jobs/LDAPAllSyncJob.php says that it syncs groups and members, but instead it appears to run the group sync twice.

I can't test this immediately, so didn't want to just make a PR that doesn't work, but you can see the two lines here that are identical. I assume the second one should be the member sync: https://github.com/silverstripe/silverstripe-ldap/blob/master/src/Jobs/LDAPAllSyncJob.php#L86

**Comment by halkyon** [comment]
Yeah, looks like a copy/paste error. This is what it looked like on the SS 3.x module: https://github.com/silverstripe/silverstripe-activedirectory/blob/master/code/jobs/LDAPAllSyncJob.php#L63

**Comment by madmatt** [comment]
Fixed with #18, closing.
