### ISSUE TITLE
Switch from using Zend to AdLdap2

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-ldap#13]
The `Zend\Ldap` module we're currently using doesn't support LDAP result pagination and it doesn't appear to be something that is being actively worked on (~2yrs with no updates but some workarounds that'd we'd need to port into this module, see zendframework/zend-ldap#41 for more info).

There is a similar library, [Adldap2/Adldap2](https://github.com/Adldap2/Adldap2) which provides more functionality while being similar in execution to `Zend\Ldap`. In particular, it supports result pagination which is currently a show-stopper that prevents LDAP users from being fully synced with SilverStripe unless you have less users than the `MaxPageSize` in AD (defaults to 1,000 - which is not very many users compared to many organisations!)

If there's no major concerns, I'll look to perform this upgrade and do a pull request into a new version of the module. Not sure yet whether this would need to be a breaking change or not, it's possible that it won't have to be as most of the lower level stuff is abstracted away.

Keen for any thoughts from existing maintainers or users.

**Comment by dhensby** [comment]
What about adding the feature to Zend? Would that be less work than switching libraries?

**Comment by madmatt** [comment]
That's definitely a possibility as well. There's already some example implementations to provide support to `Zend\Ldap` for ldap object pagination.

`Adldap2` does seem to have better docs (on the surface, maybe I'm missing something about `Zend\Ldap` though), and it appears to be more actively maintained (335 commits since 2017[1] vs. 39[2]).

This isn't necessarily a great reason to swap, but it also appears to be a lot easier to define custom schemas for <your particular flavour of LDAP> with `Adldap2` than with `Zend\Ldap`, including actual docs[3] on how to do this.

I'd be happy to have a bit of a crack at this if I get the chance, mainly to see how much effort it's likely to be. I feel like we'd be in a better place going forward with `Adldap2`, but I'm not necessarily entirely sold on the idea yet, so keen for thoughts :D

[1] https://github.com/Adldap2/Adldap2/graphs/contributors?from=2017-01-01&to=2018-06-07&type=c
[2] https://github.com/zendframework/zend-ldap/graphs/contributors?from=2017-01-01&to=2018-06-07&type=c
[3] https://github.com/Adldap2/Adldap2/blob/v8.0/docs/connecting.md#custom-schemas

**Comment by robbieaverill** [comment]
If the options were both feature parity then I wouldn't be that bothered either way. At a quick glance the Adlap2 module has a reasonable indication that it's actively supported, albeit slowing down over time and largely revolving around one person. That said, it's arguably much more popular than the Zend library at a quick glance at the same GitHub metrics.

**Comment by madmatt** [comment]
Predictably, I ran out of time a bit and ended up just adding a new iterator method to this module that extends the functionality of `zend-ldap` to support pagination for LDAP objects rather than always capping out at the maximum. I'll raise a PR for that shortly once I've confirmed it works and doesn't otherwise break BC.
