### ISSUE TITLE
Improve documentation of default_group

### ISSUE THREAD

**Issue by Amenel** [silverstripe/silverstripe-ldap#29]
This is to report that section "Put imported Member into a default group" advises to specify property `default_group` in `SilverStripe\ActiveDirectory\Services\LDAPService`. However, with that specification in place, the LDAPDebug page still complains that `default_group` is not set.

It turns out that the rest of the documentation uses `SilverStripe\LDAP\Services\LDAPService` and when I specified `default_group` in there (instead of `SilverStripe\ActiveDirectory\Services\LDAPService`), everything was fine.

Maybe that at some point in the past, LDAPService was in namespace `SilverStripe\ActiveDirectory\Services`?

**Comment by robbieaverill** [comment]
Thanks for raising this. Yes, in SilverStripe 3 it was in a module called silverstripe-activedirectory, and initially when it was upgraded to SilverStripe 4 compatible it was under that namespace. It has since been split out. Would you like to make a pull request to fix it up?

**Comment by Amenel** [comment]
Yes, please, let me submit a PR for this.

**Comment by Amenel** [comment]
I created PR #30 for this. I guess this issue can now be closed.

**Comment by robbieaverill** [comment]
Thanks for the pull request @Amenel!
